### PR TITLE
feat: Migration to MDC

### PR DESCRIPTION
**Pull request by bodnara**
* radio - no changes
* select - changed width to fit whole text
* slide toggle - no changes
* slider - not used
* snack bar - not used
* table - added bottom border to last row
* tabs - removed stretch and added bottom border to header

### CODE REVIEW

**Comment by xflord** [comment]
Screenshot from 2023-02-08 13-02-04
I'm assuming the misalignment is a mat-table issue (I guess it could be card related as well?)

Screenshot from 2023-02-08 13-35-14
Could we make the master toggle work?

Screenshot from 2023-02-08 13-35-25
The dynamically updated select text disappears when none of the selected options are on screen

**Comment by xflord** [comment]
Screenshot from 2023-02-08 13-55-51
Might just be me but the uneven border of the search field looks weird

**Comment by xflord** [comment]
Screenshot from 2023-02-08 14-04-00
when no entity is found, the search dropdown menu still has extra space at the bottom and opens up like this

**Comment by bodnara** [comment]
Some of the issues mentioned with regards to search select components are fixed in the newer version of the library (7.0.0). Don't forget to `npm i`.

**Comment by bodnara** [comment]
The card was fixed. The problem with search select components is quite complicated. In order to not stall this PR in will be tackled in different one.

**Review by xflord — APPROVED** [review]

**Pull request merged**
